### ISSUE TITLE
能否不与SSO系统对接，直接访问

### ISSUE THREAD

**Issue by shamoyouhun** [alibaba/f2etest#10]

**Comment by yaniswang** [comment]
这就需要内部自建一套账号体系了。

每次使用时都注册个新账号？

**Comment by yaniswang** [comment]
或者每次新访问时，生成一个临时账号，然后存储在cookie中，也是个方案。

不过这样的话，统计数据可能就不是非常准了。

**Comment by shamoyouhun** [comment]
SSO对接对于初次搭建来说有点难，遇到问题了
TypeError: Cannot set property 'appList' of undefined
    at /opt/f2etest/f2etest-web/control/index.js:12:26
    at Layer.handle [as handle_request] (/opt/f2etest/f2etest-web/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/f2etest/f2etest-web/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/opt/f2etest/f2etest-web/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/f2etest/f2etest-web/node_modules/express/lib/router/layer.js:95:5)
    at /opt/f2etest/f2etest-web/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/opt/f2etest/f2etest-web/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/f2etest/f2etest-web/node_modules/express/lib/router/index.js:271:10)
    at /opt/f2etest/f2etest-web/app.js:106:9
    at Layer.handle [as handle_request] (/opt/f2etest/f2etest-web/node_modules/express/lib/router/layer.js:95:5)

**Comment by yaniswang** [comment]
你这个报错信息似乎不是SSO引起的。
是不是你的配置文件没配好？
appList未定义

**Comment by shamoyouhun** [comment]
重新按步骤检查了一下配置文件，没啥问题。

**Comment by yaniswang** [comment]
看了下源代码，的确是SSO没正常工作引起的

**Comment by yaniswang** [comment]
默认改为使用内置的匿名SSO：https://github.com/alibaba/f2etest/commit/e0a777787335c5b1b80b154536a842a53f5563ca
