### ISSUE TITLE
我们没有sso服务，是否可以绕过sso做认证呀？

### ISSUE THREAD

**Issue by xuzhitong89** [alibaba/f2etest#17]
我们没有sso服务，是否可以绕过sso做认证呀？我们有ldap服务。

**Comment by yaniswang** [comment]
前几天，我更新了一个版本，增加了内置的匿名SSO，新用户访问时，自动会生成一个随机的用户名存储在cookie中，你可以试试。

如果你想对接LDAP，你可以贡献一个桥接的SSO代码。

**Comment by xuzhitong89** [comment]
启动node.js 后访问http://172.16.14.197:3000/包如下错误，您的内置sso是要启动一下吧？
TypeError: Cannot set property 'appList' of undefined
    at /data/f2etest/f2etest-web/control/index.js:12:26
    at Layer.handle [as handle_request] (/data/f2etest/f2etest-web/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/f2etest/f2etest-web/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/data/f2etest/f2etest-web/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/f2etest/f2etest-web/node_modules/express/lib/router/layer.js:95:5)
    at /data/f2etest/f2etest-web/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/data/f2etest/f2etest-web/node_modules/express/lib/router/index.js:330:12)
    at next (/data/f2etest/f2etest-web/node_modules/express/lib/router/index.js:271:10)
    at /data/f2etest/f2etest-web/app.js:108:9
    at Layer.handle [as handle_request] (/data/f2etest/f2etest-web/node_modules/express/lib/router/layer.js:95:5)

**Comment by yaniswang** [comment]
你确定用的是最新版本代码？
