### ISSUE TITLE
在f2etest-web选择IE7跳转到*.*.*.*:8080/guacamole/client.xhtml页面黑屏

### ISSUE THREAD

**Issue by ariesliu** [alibaba/f2etest#20]
你好，我按照教程部署完成后，结构是这样的：
f2etest-web部署在地址：http://192.168.137.3:3000/  上
f2etest-client部署在：http://192.168.137.4（windows server2008 standard）上

现在我访问web端，能看到我配置的IE7图标，点击后重定向到8080端口的地址，url中携带了默认的user和password等参数。

问题是：这个页面是黑屏状态，看不到任何错误信息（包括IIS和tomcat里），IIS可以单独访问。

我猜测是用户名和密码验证没有通过，但是不知道如何定位问题。数据库中可以查到用户名和密码。

麻烦有人看到能帮忙答复一下，十分感谢！

**Comment by yaniswang** [comment]
如果是密码不正确，应该会弹出一个登录窗口。

你如果是黑屏，感觉不像是这个问题。

**Comment by xxmmll** [comment]
@ariesliu 可以看看f2etest-client机上各种配置是否按说明去搭好，远程IE、bat有没有加到RemoteApp管理器里。

**Comment by ariesliu** [comment]
@xxmmll 感谢回复，我是按照issues list里面的一个朋友描述的windows server设置来弄的，关于bat设置这一块确实存在问题（一个是没找到那个sharehost.bat文件，另外也没看到remote app的配置在哪里），作者github里面的设置描述实在太简单，windows server配置太复杂。不知道有没有毕竟详细的安装过程描述呢？

**Comment by yaniswang** [comment]
密码无论正确与否，你如果单独打开:xxx.com:8080/guacamole/client.xhtml
应该都是可以出现一个登录界面。
如果没有出现，说明你的guacamole服务部署的有问题。

**Comment by xxmmll** [comment]
@ariesliu 你要试下http://ip:8080 访问tomcat是否成功，如果成功再访问http://ip:8080/guacamole是否弹出登录框，都成功就证明web部署通过了。在2008机器上打开RemoteApp管理器（在远程管理那里），点击添加新的RemoteApp，找到本地的ie.exe添加进去，属性设为任何参数可访问，再添加app文件夹里已设置好的bat文件，参数设置同上，curl要加到系统环境里，其它部署参考那个windows安装，然后再点击web里对应的ie看下是否成功。

**Comment by ariesliu** [comment]
@yaniswang @xxmmll   首先谢谢二位答复。
目前我部署过程中堵在这个地方，如下图显示。
问题：点击图中IE7的logo，重定向到一个网址后就黑屏，tomcat没有错误信息。windows server2008配置按xxmmll的提示设置了一下，见下图。由于没有错误信息，实在不知道从何入手了，感谢援手！


![1](https://cloud.githubusercontent.com/assets/104354/11928503/0e9b201a-a80f-11e5-881b-659f5b3df2ea.jpg)
![2](https://cloud.githubusercontent.com/assets/104354/11928502/0e969b1c-a80f-11e5-998d-9447525dfebe.jpg)
![3](https://cloud.githubusercontent.com/assets/104354/11928501/0e95d10a-a80f-11e5-87de-35d14ed6270b.jpg)
![4](https://cloud.githubusercontent.com/assets/104354/11928504/0e9b49c8-a80f-11e5-9a68-9386f4a53037.jpg)

**Comment by yaniswang** [comment]
不要用360浏览器连接啊，用chrome,firefox, ie 10以上等新浏览器。

你那个黑屏，有可能是浏览器不支持。

**Comment by ariesliu** [comment]
@yaniswang hi你好，我试了几个浏览器都是这样的状况。。。

**Comment by yaniswang** [comment]
@ariesliu 有没有可能是某个guacamole组件没安装好？

**Comment by yaniswang** [comment]
你那个登录界面也不正确，如果使用了我们定制版本的话，应该是不需要登录的。

**Comment by ariesliu** [comment]
我直接在8080地址guacamole登录页面随便输入账户密码，tomcat日志会提示：
SEVERE: Error reading Guacamole configuration.
org.glyptodon.guacamole.GuacamoleException: Authentication provider class not found
        at org.glyptodon.guacamole.net.basic.properties.AuthenticationProviderProperty.parseValue(AuthenticationProviderProperty.java:59)
        at org.glyptodon.guacamole.net.basic.properties.AuthenticationProviderProperty.parseValue(AuthenticationProviderProperty.java:37)
        at org.glyptodon.guacamole.properties.GuacamoleProperties.getProperty(GuacamoleProperties.java:150)
        at org.glyptodon.guacamole.properties.GuacamoleProperties.getRequiredProperty(GuacamoleProperties.java:198)
        at org.glyptodon.guacamole.net.basic.AuthenticatingHttpServlet.init(AuthenticatingHttpServlet.java:106)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:864)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:134)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
---------------------------------------------------------------------------
我的资源文件配置如下：
[root@localhost logs]# cat /etc/guacamole/guacamole.properties 
# Hostname and port of guacamole proxy
guacd-hostname: 192.168.137.3
guacd-port:     4822
enable-websocket: true
enable-clipboard-integration: true

auth-provider: net.sourceforge.guacamole.net.auth.noauth.NoAuthenticationProvider
noauth-config: /etc/guacamole/noauth-config.xml

# auth-provider: net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
# basic-user-mapping: /etc/guacamole/user-mapping.xml


PS:
请问 @yaniswang 有没有群（QQ或旺旺）提供支持啊？

**Comment by ariesliu** [comment]
Caused by: java.lang.ClassNotFoundException: net.sourceforge.guacamole.net.auth.noauth.NoAuthenticationProvider
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1854)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1703)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:191)
        at org.glyptodon.guacamole.net.basic.GuacamoleClassLoader.findClass(GuacamoleClassLoader.java:165)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.glyptodon.guacamole.net.basic.properties.AuthenticationProviderProperty.parseValue(AuthenticationProviderProperty.java:49)
        ... 23 more

**Comment by yaniswang** [comment]
刚建了个群，QQ群号：416221937

从你的信息来看，是NoAuthenticationProvider有问题。

**Comment by ariesliu** [comment]
在 @yaniswang 帮助下找到原因了，作者对guacamole.war做了专门的定制，我之前自己部署过guacamole环境，都是从官网下载的，因此提示找不到net.sourceforge.guacamole.net.auth.noauth里面的类，查看tomcat的webapps目录下的项目，发现该目录中确实没有NoAuthenticationProvider.java文件，使用作者的war包就可以了。

另外windows server配置是参考 @xxmmll  设置的，谢谢二位！
