### ISSUE TITLE
node server error

### ISSUE THREAD

**Issue by Sunqinying** [alibaba/f2etest#40]
Error: Failed to lookup view "index" in views directory "/root/f2etest-web/views"
   at EventEmitter.app.render (/root/f2etest-web/node_modules/express/lib/application.js:555:17)
   at ServerResponse.res.render (/root/f2etest-web/node_modules/express/lib/response.js:938:7)
   at /root/f2etest-web/control/index.js:15:13
   at Layer.handle [as handle_request] (/root/f2etest-web/node_modules/express/lib/router/layer.js:82:5)
   at next (/root/f2etest-web/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/root/f2etest-web/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/root/f2etest-web/node_modules/express/lib/router/layer.js:82:5)
   at /root/f2etest-web/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/root/f2etest-web/node_modules/express/lib/router/index.js:321:12)
   at next (/root/f2etest-web/node_modules/express/lib/router/index.js:261:10)

**Comment by Sunqinying** [comment]
访问 node server 地址的时候， 会报这个错。

**Comment by yaniswang** [comment]
你是怎么执行命令的？

**Comment by Stngle** [comment]
参考文档：https://alibaba.github.io/f2etest/build/#/artist/f2etest/f2etest-web-install
