### ISSUE TITLE
You have been disconnected. Reload the page to reconnect.

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/f2etest#52]
点击浏览器，跳转到guacamole 提示 You have been disconnected. Reload the page to reconnect.

是哪里有问题么？还是就应该是这样的？目前只部署了浏览器云，还没弄webdriver云

tomcat日志：
`Dec 20, 2017 2:17:35 PM org.slf4j.impl.JCLLoggerAdapter error
SEVERE: Error connecting WebSocket tunnel.
org.glyptodon.guacamole.GuacamoleServerException: java.net.ConnectException: Connection refused
	at org.glyptodon.guacamole.net.InetGuacamoleSocket.<init>(InetGuacamoleSocket.java:119)
	at org.glyptodon.guacamole.net.auth.simple.SimpleConnection.connect(SimpleConnection.java:126)
	at org.glyptodon.guacamole.net.basic.BasicTunnelRequestUtility.createTunnel(BasicTunnelRequestUtility.java:301)
	at org.glyptodon.guacamole.net.basic.websocket.tomcat.BasicGuacamoleWebSocketTunnelServlet$1.doConnect(BasicGuacamoleWebSocketTunnelServlet.java:48)
	at org.glyptodon.guacamole.net.basic.websocket.tomcat.GuacamoleWebSocketTunnelServlet.createWebSocketInbound(GuacamoleWebSocketTunnelServlet.java:84)
	at org.glyptodon.guacamole.net.basic.websocket.tomcat.BasicGuacamoleWebSocketTunnelServlet.authenticatedConnect(BasicGuacamoleWebSocketTunnelServlet.java:56)
	at org.glyptodon.guacamole.net.basic.websocket.tomcat.AuthenticatingWebSocketServlet.createWebSocketInbound(AuthenticatingWebSocketServlet.java:142)
	at org.apache.catalina.websocket.WebSocketServlet.doGet(WebSocketServlet.java:125)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.glyptodon.guacamole.net.basic.websocket.tomcat.AuthenticatingWebSocketServlet.service_websocket_request(AuthenticatingWebSocketServlet.java:110)
	at org.glyptodon.guacamole.net.basic.websocket.tomcat.AuthenticatingWebSocketServlet.access$000(AuthenticatingWebSocketServlet.java:45)
	at org.glyptodon.guacamole.net.basic.websocket.tomcat.AuthenticatingWebSocketServlet$1.authenticatedService(AuthenticatingWebSocketServlet.java:65)
	at org.glyptodon.guacamole.net.basic.AuthenticatingHttpServlet.service(AuthenticatingHttpServlet.java:372)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.glyptodon.guacamole.net.basic.websocket.tomcat.AuthenticatingWebSocketServlet.service(AuthenticatingWebSocketServlet.java:91)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by luoxi001713** [comment]
是安装guacamole缺少依赖包，重新安装解决。

**Comment by LiPinghai** [comment]
@luoxi001713 遇到一样情况，请问是缺少哪些依赖？

**Comment by undead25** [comment]
@LiPinghai 加钉钉群：30684524
