### ISSUE TITLE
f2etest-web初始化用户失败

### ISSUE THREAD

**Issue by fengshenhai-0727** [alibaba/f2etest#68]
http://172.16.235.72/setuser.asp?key=f2etest-client-api-key&username=User1528684276905&password=X5ce681ec79a1ffeb7ae6a7d9288debc7 返回ok

但 f2etest-web/lib/initUser.js中的 request('http://172.16.235.72/setuser.asp***',function(error,**,**){
      console.log(error);

})
error = > 

{ Error: connect ETIMEDOUT 172.16.235.72:80
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.16.235.72',
  port: 80 }
request undefined
{ Error: connect ETIMEDOUT 172.16.235.74:80
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.16.235.74',
  port: 80 }
request undefined
{ Error: connect ETIMEDOUT 172.16.235.73:80
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.16.235.73',
  port: 80 }

**Comment by yaniswang** [comment]
是否linux那台机器上无法访问这个URL？你可以到那台机器上测试下

**Comment by fengshenhai-0727** [comment]
问题已解决，是两台机器之前能访问，之后不能访问导致的
