### ISSUE TITLE
怎么控制多个用户同时访问

### ISSUE THREAD

**Issue by rain-beaver** [alibaba/f2etest#69]
现在最多找开4个浏览器页面，打开第5个其它已经打开的就会断开了，这个是哪里的问题

**Comment by yaniswang** [comment]
你没安装授权服务器

**Comment by rain-beaver** [comment]
谢谢您的回复，授权服务器有安装教程吗？我是两台机器，最多打开4个页面，就打不开第5个了

**Comment by yaniswang** [comment]
网上自己搜索教程

**Comment by rain-beaver** [comment]
好的，非常感谢！

**Comment by rain-beaver** [comment]
回顾了下操作，之前授权服务器我装过，装了还是没有起作用

**Comment by yaniswang** [comment]
装了后，要在RDP设置界面指定这个授权服务器

**Comment by rain-beaver** [comment]
我是server2003与server2008，相当于是每台server都得这么操作吗

**Comment by rain-beaver** [comment]
我排查了一下，如果我单独远程桌面两台服务器，同一个用户可以远程10多个桌面没问题，但通过web页面打开就不行，最多的4个，报错也只有tomcat的

> 11-Aug-2018 08:19:47.029 SEVERE [http-nio-8080-exec-3] org.slf4j.impl.JCLLoggerAdapter.error Internal server error.
 org.glyptodon.guacamole.GuacamoleServerException: java.net.SocketException: Connection reset
	at org.glyptodon.guacamole.io.ReaderGuacamoleReader.read(ReaderGuacamoleReader.java:186)
	at org.glyptodon.guacamole.io.ReaderGuacamoleReader.readInstruction(ReaderGuacamoleReader.java:195)
	at org.glyptodon.guacamole.net.basic.MonitoringGuacamoleReader.readInstruction(MonitoringGuacamoleReader.java:89)
	at org.glyptodon.guacamole.net.basic.MonitoringGuacamoleReader.read(MonitoringGuacamoleReader.java:77)
	at org.glyptodon.guacamole.servlet.GuacamoleHTTPTunnelServlet.doRead(GuacamoleHTTPTunnelServlet.java:308)
	at org.glyptodon.guacamole.servlet.GuacamoleHTTPTunnelServlet.handleTunnelRequest(GuacamoleHTTPTunnelServlet.java:190)
	at org.glyptodon.guacamole.servlet.GuacamoleHTTPTunnelServlet.doGet(GuacamoleHTTPTunnelServlet.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.glyptodon.guacamole.net.basic.BasicGuacamoleTunnelServlet.authenticatedService(BasicGuacamoleTunnelServlet.java:115)
	at org.glyptodon.guacamole.net.basic.AuthenticatingHttpServlet.service(AuthenticatingHttpServlet.java:372)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at org.glyptodon.guacamole.io.ReaderGuacamoleReader.read(ReaderGuacamoleReader.java:172)
	... 33 more

**Comment by rain-beaver** [comment]
我又测试了一个场景，多个不同浏览器分别打开4个页面，谁都不会掉线，只是单个浏览器只能打开的个页面，我觉得授权服务器应该是启动了，我不知道在哪里改单个浏览器打开页面的限制，另外Safari浏览器首页能进入，但打开各个浏览器的页面没有响应，后台也没有报错

**Comment by rain-beaver** [comment]
应该是浏览器的事情，每个浏览器允许打开的页面都不太一样
